// <auto-generated />
namespace SOPeL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tab_pac_dok_tozsamosci2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tab_pac_dok_tozsamosci2));
        
        string IMigrationMetadata.Id
        {
            get { return "201611291457445_tab_pac_dok_tozsamosci2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
