// <auto-generated />
namespace SOPeL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_Filip_baza : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Filip_baza));
        
        string IMigrationMetadata.Id
        {
            get { return "201611031710581_update_Filip_baza"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
